import Head from "next/head";
import Image from "next/image";

import styled from "styled-components";

const MainContainer = styled.main`
  width: 100vw;
  height: 100vh;
  padding-top: 20px;
`;

const LogoSection = styled.section`
  display: flex;
  flex-direction: column;
  justify-content: center;
  align-items: center;
  gap: 20px;
`;

const Descrition = styled.h3`
  font-size: 50px;
  color: #384f93;
`;

const LankSection = styled.section`
  width: 100%;
  height: auto;
  margin-top: 20px;
  padding: 40px;
`;

const LankCard = styled.div`
  width: 500px;
  height: auto;
`;

const ImageCard = styled.img`
  width: 100%;
  height: auto;
  border-radius: 8px;
  box-shadow: 2px 2px 2px gray;
`;

export default function Home() {
  console.log("hello");
  return (
    <>
      <Head>
        <title>Nut2</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <MainContainer>
        <LogoSection>
          <Image
            src="/images/nut.png"
            alt="Nut메인 이미지"
            width={430}
            height={300}
          />
          <Descrition>Style community Nut2</Descrition>
        </LogoSection>
        <LankSection>
          <LankCard>
            <ImageCard src="/images/fastion0.jpg" alt="패션1" />
          </LankCard>
        </LankSection>
      </MainContainer>
    </>
  );
}
