import Head from "next/head";
import styled from "styled-components";

// Components
import Slick from "@/components/ui/slick";

// react-slick css
import "slick-carousel/slick/slick.css";
import "slick-carousel/slick/slick-theme.css";

// Mui Icon
import SearchIcon from "@mui/icons-material/Search";

const MainContainer = styled.main`
  width: 100%;
  height: 100%;
`;

const ModelSection = styled.section`
  width: 100%;
  height: auto;
  margin-top: 50px;
  padding: 0px 230px;
`;

const CardBox = styled.div`
  display: flex;
  gap: 20px;
`;
const LankCard = styled.div`
  display: flex;
  gap: 20px;
  width: 25%;
  height: auto;
`;

const ImageCard = styled.img`
  width: 100%;
  height: auto;
  border-radius: 8px;
  box-shadow: 0px 4px 4px rgba(0, 0, 0, 0.25);
  object-fit: cover;
`;

const StyleViewBtnSec = styled.article`
  margin-bottom: 20px;
  width: 100%;
`;

const ViewButton = styled.button`
  display: flex;
  align-items: center;
  justify-content: center;
  width: 100%;
  background-color: #1363df;
  border: 0px;
  height: 70px;
  border-radius: 50px;
  color: #eeeeee;
  font-size: 20px;
  cursor: pointer;
`;

export async function getServerSideProps() {
  try {
    let response = await fetch("http://localhost:3000/api/nut2");
    let posts = await response.json();
    return {
      props: { posts: JSON.parse(JSON.stringify(posts)) },
    };
  } catch (e) {
    console.error(e);
  }
}

export default function Home() {
  return (
    <>
      <Head>
        <title>Nut2</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <MainContainer>
        <div>
          <Slick />
        </div>

        <ModelSection>
          <StyleViewBtnSec>
            <ViewButton>
              <SearchIcon /> 모델 스타일 보러가기
            </ViewButton>
          </StyleViewBtnSec>
          <CardBox>
            <LankCard>
              <ImageCard src="/images/fastion0.jpg" alt="패션1" />
            </LankCard>
            <LankCard>
              <ImageCard src="/images/fastion0.jpg" alt="패션1" />
            </LankCard>
          </CardBox>
        </ModelSection>
      </MainContainer>
    </>
  );
}
